In [4]:
import numpy as np

In [92]:
import pandas as pd

#### **Задание 1**
#### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [93]:
def create_array(n):
    result =[]
    while n >= 0:
        result.append(n)
        n-=1
    a = np.array(result)
    return a
create_array(10)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### **Задание 2**
#### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [88]:
def diag_matrix(n):
    a = np.diag(np.arange(n))
    cnt = 0
    while n >= 0:
        n-=1
        cnt+= n
    cnt+=1 #в таком подсчёте не хватает единицы
    b = a[::-1, ::-1]
    print(cnt)
    return b
diag_matrix(5)

10


array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

#### **Задание 3**
#### Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [94]:
movies = pd.read_csv('movies.csv')
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [95]:
ratings = pd.read_csv('ratings.csv')
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [96]:
joined = ratings.merge(movies, on='movieId', how='left')
joined.head()

userId  movieId  rating  timestamp                        title  \
0       1        1     4.0  964982703             Toy Story (1995)   
1       1        3     4.0  964981247      Grumpier Old Men (1995)   
2       1        6     4.0  964982224                  Heat (1995)   
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)   
4       1       50     5.0  964982931   Usual Suspects, The (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                               Comedy|Romance  
2                        Action|Crime|Thriller  
3                             Mystery|Thriller  
4                       Crime|Mystery|Thriller

In [97]:
joined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100836 entries, 0 to 100835
Data columns (total 6 columns):
userId       100836 non-null int64
movieId      100836 non-null int64
rating       100836 non-null float64
timestamp    100836 non-null int64
title        100836 non-null object
genres       100836 non-null object
dtypes: float64(1), int64(3), object(2)
memory usage: 5.4+ MB


In [98]:
del joined['timestamp']
del joined['genres']

In [99]:
joined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100836 entries, 0 to 100835
Data columns (total 4 columns):
userId     100836 non-null int64
movieId    100836 non-null int64
rating     100836 non-null float64
title      100836 non-null object
dtypes: float64(1), int64(2), object(1)
memory usage: 3.8+ MB


In [103]:
joined.duplicated().sum()

0

In [104]:
joined.isna().sum()

userId     0
movieId    0
rating     0
title      0
dtype: int64

In [106]:
del joined['movieId']

In [107]:
joined.tail()

userId  rating                           title
100831     610     4.0                    Split (2017)
100832     610     5.0   John Wick: Chapter Two (2017)
100833     610     5.0                  Get Out (2017)
100834     610     5.0                    Logan (2017)
100835     610     3.0  The Fate of the Furious (2017)

In [110]:
max_rate_joined = joined[joined['rating'] == 5.0]
max_rate_joined.tail()

userId  rating                          title
100814     610     5.0           The Nice Guys (2016)
100829     610     5.0                 Arrival (2016)
100832     610     5.0  John Wick: Chapter Two (2017)
100833     610     5.0                 Get Out (2017)
100834     610     5.0                   Logan (2017)

In [119]:
max_rate_sum = max_rate_joined['rating'].groupby(max_rate_joined['title']).count()
max_rate_sum.sort_values(ascending = False).head(1)

title
Shawshank Redemption, The (1994)    153
Name: rating, dtype: int64

#### **Задание 4**
#### По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [42]:
df = pd.read_csv('power.csv')

In [55]:
filtered_df = df[((df['country'] == 'Lithuania') | (df['country'] == 'Latvia') | (df['country'] == 'Estonia')) & ((df['category'] == 4) | (df['category'] == 12) | (df['category'] == 21)) & ((df['year'] >=2005) & (df['year'] <=2010)) & (df['quantity'] >= 0)]
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 408 entries, 10617 to 253986
Data columns (total 4 columns):
country     408 non-null object
year        408 non-null int64
quantity    408 non-null float64
category    408 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 15.9+ KB


In [56]:
print(filtered_df.duplicated().sum())

131


In [60]:
filtered_df = filtered_df.drop_duplicates().reset_index(drop=True)
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 4 columns):
country     277 non-null object
year        277 non-null int64
quantity    277 non-null float64
category    277 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 8.7+ KB


In [61]:
na_number = filtered_df.isna().sum()
na_number

country     0
year        0
quantity    0
category    0
dtype: int64

In [65]:
result_df = filtered_df['quantity'].sum()
result_df

223450.0

#### **Задание 5**
#### Решите систему уравнений:
#### 4x + 2y + z = 4
#### x + 3y = 12
#### 5y + 4z = -3

In [6]:
from numpy import linalg

In [8]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])

In [9]:
b = np.array([4, 12, -3])

In [10]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [11]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True